version: '3.5'

services:
  drill:
      image: drill/apache-drill:latest
      stdin_open: true
      tty: true
      ports:
          - "8047:8047"
      volumes:
          - "D:/datalake:/data"
  superset:
      build:
          context: ./superset
      ports:
          - "8088:8088"
      command: gunicorn superset:app -t 300
volumes:
  data: